# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 02:02
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dishonesty_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsession',
            name='multiplier',
        ),
        migrations.AddField(
            model_name='subsession',
            name='bonus_multiplier',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
