# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 02:23
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dishonesty_app', '0002_auto_20180304_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='should_keep',
            field=otree.db.models.CurrencyField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], null=True, verbose_name='I understand that the amount of random number advise me to allocate this amount'),
        ),
    ]
