# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-09 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.currency
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dishonesty_app', '0004_auto_20180308_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_choice', otree.db.models.IntegerField(null=True)),
                ('answer', otree.db.models.IntegerField(choices=[(otree.currency.Currency('10'), otree.currency.Currency('10')), (otree.currency.Currency('20'), otree.currency.Currency('20')), (otree.currency.Currency('30'), otree.currency.Currency('30')), (otree.currency.Currency('40'), otree.currency.Currency('40')), (otree.currency.Currency('50'), otree.currency.Currency('50')), (otree.currency.Currency('60'), otree.currency.Currency('60')), (otree.currency.Currency('70'), otree.currency.Currency('70')), (otree.currency.Currency('80'), otree.currency.Currency('80')), (otree.currency.Currency('90'), otree.currency.Currency('90')), (otree.currency.Currency('100'), otree.currency.Currency('100'))], null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='dishonesty_app.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='guess',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_10',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_100',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_20',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_30',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_40',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_50',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_60',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_70',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_80',
        ),
        migrations.RemoveField(
            model_name='group',
            name='response_90',
        ),
    ]
