# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-09 01:04
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dishonesty_app', '0006_player_dump_guess_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dump_guess_answer',
            field=otree.db.models.LongStringField(null=True),
        ),
    ]
