# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 23:14
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dishonesty_app', '0008_auto_20180308_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='is_real_effort_task_treatment',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='group',
            name='should_keep',
            field=otree.db.models.CurrencyField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], null=True, verbose_name='I understand that the random number advises me to allocate this amount'),
        ),
        migrations.AlterField(
            model_name='player',
            name='dump_guess_answer',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
